language: python

cache:
  - pip
  - $HOME/.cache/pypoetry

python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
install:
  - make dev
# command to run tests
script:
  - make test # or py.test for Python versions 3.5 and below
after_success:
  - coveralls
