language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - make dev
# command to run tests
script:
  - make test # or py.test for Python versions 3.5 and below