"""A setuptools based setup module.
See:
https://packaging.python.org/en/latest/distributing.html
https://github.com/pypa/sampleproject
Autogenerated by poetry-setup:
https://github.com/orsinium/poetry-setup
"""
# IMPORTANT: this file is autogenerated. Do not edit it manually.
# All changes will be lost after `poetry-setup` command execution.
# ----------------------------------------------------------------
# Always prefer setuptools over distutils
from setuptools import setup, find_packages
from os import path
# io.open is needed for projects that support Python 2.7
# It ensures open() defaults to text mode with universal newlines,
# and accepts an argument to specify the text encoding
# Python 3 only projects can skip this import
from io import open
here = path.abspath(path.dirname(__file__))
# Get the long description from the README file
with open(path.join(here, 'README.md'), encoding='utf-8') as f:
    long_description = f.read()
# Arguments marked as "Required" below must be included for upload to PyPI.
# Fields marked as "Optional" may be commented out.
setup(
    # https://packaging.python.org/specifications/core-metadata/#name
    name='triflow',  # Required
    # https://www.python.org/dev/peps/pep-0440/
    # https://packaging.python.org/en/latest/single_source_version.html
    version='0.6.0',  # Required
    # https://packaging.python.org/specifications/core-metadata/#summary
    description="Automatic finite difference discretization for 1D PDE with fast temporal solvers.",  # Required
    # https://packaging.python.org/specifications/core-metadata/#description-optional
    long_description=long_description,  # Optional
    # https://packaging.python.org/specifications/core-metadata/#description-content-type-optional
    long_description_content_type='text/markdown',  # Optional (see note above)
    author="Nicolas Cellier",  # Optional
    author_email="contact@nicolas-cellier.net",  # Optional
    # For a list of valid classifiers, see https://pypi.org/classifiers/
    classifiers=[
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7'
    ],  # Optional
    keywords=' '.join(
        ['PDE', 'finite-difference', 'physic', 'modelling',
         'interactive']),  # Optional
    packages=find_packages(),  # Required
    # https://packaging.python.org/en/latest/requirements.html
    install_requires=[
        'numpy (>=1,<2)',
        'scipy (>=1,<2)',
        'sympy (>=1.3,<2.0)',
        'streamz (>=0.3,<0.4)',
        'more-itertools (>=4,<5)',
        'xarray (>=0.10,<0.11)',
        'dask (>=0.18,<0.19)',
        'pyyaml (>=3,<4)',
        'joblib (>=0.12,<0.13)',
        'path.py (>=11,<12)',
        'tqdm (>=4,<5)',
        'cloudpickle (>=0.5.2,<0.6.0)',
        'attrs (>=18.1,<19.0)',
        'sklearn (>=0,<1)',
        'matplotlib (>=3,<4)',
        'holoviews (>=1,<2)',
        'boltons (>=18.0,<19.0)',
        'fuzzywuzzy (>=0.17.0,<0.18.0)',
        'python-Levenshtein (>=0.12.0,<0.13.0)',
        'pylama (>=7,<8)',
        'isort (>=4,<5)',
        'black (>=18,<19)',
        'pytest (>=3,<4)',
        'sphinx',
        'matplotlib (>=3,<4)',
        'python-coveralls (>=2,<3)',
        'pytest-cov (>=2,<3)',
        'ipykernel (>=5.1,<6.0)',
        'poetry-setup (>=0.3.5,<0.4.0)',
    ],  # Optional
    # https://setuptools.readthedocs.io/en/latest/setuptools.html#dependencies-that-aren-t-in-pypi
    dependency_links=[],  # Optional
    # https://stackoverflow.com/a/16576850
    include_package_data=True,
    # https://packaging.python.org/specifications/core-metadata/#project-url-multiple-use
    project_urls={  # Optional
    },
)
